services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot_lien.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: GROUP_ID
        sync: false
      - key: OWNER_ID
        sync: false
      - key: WEBHOOK_URL
        sync: false
